"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.env = void 0;
const zod_1 = require("zod");
const envSchema = zod_1.z.object({
    NODE_ENV: zod_1.z.enum(['development', 'test', 'production']).default('development'),
    PORT: zod_1.z.string().default('5000'),
    MONGO_URI: zod_1.z.string().min(1, 'MONGO_URI is required'),
    JWT_ACCESS_SECRET: zod_1.z.string().min(30, 'JWT_ACCESS_SECRET is required'),
    JWT_REFRESH_SECRET: zod_1.z.string().min(30, 'JWT_REFRESH_SECRET is required'),
    COOKIE_DOMAIN: zod_1.z.string().optional(),
    COOKIE_SAMESITE: zod_1.z.enum(['lax', 'none', 'strict']).optional(),
    FRONTEND_ORIGIN: zod_1.z.string().min(1, 'FRONTEND_ORIGIN is required'),
    CORS_ADDITIONAL_ORIGINS: zod_1.z.string().optional(),
    CORS_ALLOW_VERCEL_WILDCARD: zod_1.z.string().optional(),
    APP_BASE_URL: zod_1.z.string().optional(),
    BACKEND_BASE_URL: zod_1.z.string().optional(),
    EMAIL_HOST: zod_1.z.string().optional(),
    EMAIL_PORT: zod_1.z.string().optional(),
    EMAIL_USER: zod_1.z.string().optional(),
    EMAIL_PASS: zod_1.z.string().optional(),
    GOOGLE_CLIENT_ID: zod_1.z.string().optional(),
    GOOGLE_CLIENT_SECRET: zod_1.z.string().optional(),
    AWS_REGION: zod_1.z.string().optional(),
    S3_BUCKET: zod_1.z.string().optional(),
    STRIPE_SECRET_KEY: zod_1.z.string().optional(),
    STRIPE_WEBHOOK_SECRET: zod_1.z.string().optional(),
});
exports.env = envSchema.parse({
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    MONGO_URI: process.env.MONGO_URI,
    JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    COOKIE_DOMAIN: process.env.COOKIE_DOMAIN,
    COOKIE_SAMESITE: process.env.COOKIE_SAMESITE,
    FRONTEND_ORIGIN: process.env.FRONTEND_ORIGIN,
    CORS_ADDITIONAL_ORIGINS: process.env.CORS_ADDITIONAL_ORIGINS,
    CORS_ALLOW_VERCEL_WILDCARD: process.env.CORS_ALLOW_VERCEL_WILDCARD,
    APP_BASE_URL: process.env.APP_BASE_URL,
    BACKEND_BASE_URL: process.env.BACKEND_BASE_URL,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_PORT: process.env.EMAIL_PORT,
    EMAIL_USER: process.env.EMAIL_USER,
    AWS_REGION: process.env.AWS_REGION,
    S3_BUCKET: process.env.S3_BUCKET,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    EMAIL_PASS: process.env.EMAIL_PASS,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
});
//# sourceMappingURL=env.js.map